baseURL = "https://hugo-paper.vercel.app/"
title = "Home"
author = "Steve Francia"
copyright = "© 2024, huyhunhngc"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.disqus]
    shortname = 'low'     # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'huyhn12'               # twitter.com/YOUR_TWITTER_ID
  github = 'huyhunhngc'                 # github.com/YOUR_GITHUB_ID
  instagram = 'huyhunhngc'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'huynh-ngoc-huy-732a801b0'             # linkedin.com/in/YOUR_LINKEDIN_ID
  threads = '@huyhunhngc'              # threads.net/@YOUR_THREADS_ID                             # show rss icon

  # home page profile
  title = 'Home'
  avatar = 'https://avatars.githubusercontent.com/u/46745326?v=4'                 # gravatar email or image url
  name = 'Huynh Ngoc Huy'
  bio = 'huyhunhngc'

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = false              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://imgcdn.dev/i/XixMn'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  direction = "ltr"                         # RTL support for Right-to-left languages

  # giscus
[params.giscus]
  repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
  repoId = 'YOUR_GISCUS_REPO_ID'
  category = 'YOUR__GISCUS_CATEGORY'
  categoryId = 'YOUR_GISCUS_CATEGORY_ID'
  mapping = 'pathname'
  theme = 'light'
  lang = 'zh-CN'